# -*- coding: utf-8 -*-
"""calculator_2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199flB6JJ4fgLygJH3YF5RJQ16AXS0e2t
"""

#python -m pip install streamlit

import streamlit as st

st.title("Simple Calculator")

num1 = st.number_input("Enter first number:", value=0)
num2 = st.number_input("Enter second number:", value=0)

operation = st.selectbox("Choose operation:", ["Add", "Subtract", "Multiply", "Divide"])

if st.button("Calculate"):
    if operation == "Add":
        st.success(f"Result: {num1 + num2}")
    elif operation == "Subtract":
        st.success(f"Result: {num1 - num2}")
    elif operation == "Multiply":
        st.success(f"Result: {num1 * num2}")
    elif operation == "Divide":
        if num2 != 0:
            st.success(f"Result: {num1 / num2}")
        else:
            st.error("Cannot divide by zero!")



#python -m streamlit run calc.py